### ISSUE TITLE
Fetching multiple nuxt-content folders

### ISSUE THREAD

**Issue by pimhooghiemstra** [Krutie/infinite-masonry-with-nuxt#1]
Dear Krutie,

Loved the article and the way you explain the concepts. I was wondering if it's possible to make this Pinterest like infinite scroll work if my content is in deeper nested folders.

Suppose my content folder looks like this:
content/blog/technical
content/blog/personal
content/blog/e-books

I would like to build something similar to what you did but show the most recent article on top, regardless from which content folder it originates. 

I guess the fetch or asyncData function should be changed, but I think it will take a lot of queries to find out the order of the articles. And you'll have to repeat that on every scroll. Do you have any thoughts on that?

**Comment by Krutie** [comment]
Thanks Pim! I'm glad you found my article useful. 

Yes, we can certainly fetch the content from nested folders and collectively sort them, too.

- We can use `{ deep: true }` option to avoid writing multiple  queries and fetch markdown files from nested folders.
- Then, we can use chainable function `sortBy("date")` to pass the desired sort key.  

```js
const posts = await $content("/blog", { deep: true })
                    .sortBy("date")
                    .fetch();
```
 You may want to checkout this [CodeSandbox](https://codesandbox.io/s/nested-content-demo-nuxt-content-module-8ev7x) to see the example I made to demonstrate your _exact_ use-case. 

Reference: [Nuxt Content Module Docs](https://content.nuxtjs.org/advanced#static-site-generation)

**Comment by pimhooghiemstra** [comment]
Thanks for your response Krutie!

I didn't know about the _deep_ option, but I'll have a look at it. First I need to put my content in a root directory, because currently I have 5 directories in /content and I think for your solution to work I need a single root folder with my directories in it.

I very much like the way you answered my question by even providing a sandbox with code: very helpful!
